baseURL = "https://Mascrime.github.io/carnet-des-reponses/"

title   = "Carnet des Réponses"
paginate = 10

# ← IMPORTANT : déclare Ananke comme MODULE (pas un dossier local)
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

[params]
  description = "Q/R éditées automatiquement"
  show_reading_time = true

[outputs]
  home = ["HTML","RSS","JSON"]
